apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: proman
  name: proman
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000

  selector:
    io.kompose.service: proman
  type: LoadBalancer
status:
  loadBalancer: {}
